version: "3.9"


services:
  redis:
    restart: always
    container_name: redis1
    image: "redis"
    ports:
      - "6379:6379"
  rabbitmq:
     image: "rabbitmq:3.10"
     container_name: rabbitmq
     ports:
       - "5672:5672"
       - "15672:15672"